jobs:
  docker_build:
    docker:
      - image: devdemisto/dockerbuild:1.0.0.26145
    steps:
      - checkout
      - run:
          name: Validate Approved Licenses File
          command: python -m jsonschema -i docker/approved_licenses.json docker/approved_licenses.schema.json
      - setup_remote_docker:
          version: 20.10.6
      - add_ssh_keys:
          fingerprints:
            - 46:c2:72:91:9d:0e:2d:3c:93:d6:6c:12:31:df:8e:db
      - run:
          name: Validate Images and Dependabot
          command: python -m test_pipfile_all
      - run:
          name: Run Ironabnk Unit Tests
          command: python -m pytest ironbank -v
      - run:
          name: Build Docker Images
          command: ./docker/build_docker.sh
      - store_artifacts:
          path: artifacts
          destination: docker_images
      - run:
          name: Build Ironbank Docker Images
          command: python -m ./ironbank/build_ironbank_docker.sh --python 3.9
      - store_artifacts:
          path: artifacts
          destination: ironbank_docker_images
workflows:
  version: 2
  full_build:
    jobs:
      - docker_build
